language: python
python:
- '2.7'
branches:
  except:
  - gh-pages
install:
- pip install -r requirements.txt
script:
- git clone https://github.com/getpelican/pelican-plugins.git official_plugins
- ls official_plugins
- git clone https://github.com/glasslion/pelican-zha.git ../pelican-zha
after_success:
- make github_travis
env:
  global:
    secure: ES1BnvznN4aK32g8t72z1dz39oXvA30RNtnZPAJhgBvAtm8ImwxImquYB/9A9r2zi9ujWVQdxFxBy6+jLzEvL5i6g393ENZ9uYpSi7SKCrCLPDt4AsVLnxyBw8yw1WD93HRlgYkXBa6tflI+hv1CHbt6EIhoD4o7YdkDGup0ExE=
